#!/bin/python3

alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

key = 13

character = input('please enter a character: ')

position = alphabet.find(character)
print(position)

newPosition = (position + key) % 52
print(newPosition)
